site_name: Essential skills for reproducible research computing
pages:
    - Home: index.md
    - UNIX Command Line:
        - Setup: nix/setup.md
        - Navigation: nix/navigation.md
        - File Creation and Editing: nix/file_handling.md
        - Redirection: nix/redirection.md
        - Piping: nix/pipes.md
        - man and less: nix/man_and_less.md
        - Uber exercise: nix/uber.md
        - Cheat Sheet: nix/unix_cheat_sheet.md
    - (I)Python: 
        - Python: python/python.md
        - _slicing_solution: python/solutions/python.slicing.soln.md
        - _dict_solution: python/solutions/python.dict.count.soln.md
        - _ball_solution: python/solutions/python.ball.soln.md
    - Software Licensing:
        - Open Licensing: openlicenses/openlicensing.md
    - git:
        - git: git/git.md
        - GitHub:
            - push and pull: git/github1.md
            - merging: git/merge.md
            - conflicts: git/conflicts.md
        - GitHub Collaboration: git/github2.md
        - Branch and Merge: git/branching.md
    - Jupyter:
        - Navigating the notebook: jupyter/the_notebook.md
        - The Python Scientific Stack: jupyter/1.md
    - Laplace:
        - Elliptic PDEs: laplace/1.md
    - Numba:
        - Profiling: numba/1.md
        - Intro to JIT: numba/2.md
        - Numba Internals: numba/3.md
        - CFD Intro: numba/4.md
        - Cavity Flow: numba/5.md
        - vectorize: numba/6.md
    - References:
        - References: references.md
    - Resources and Tips:
        - Resources: resources.md

extra_javascript: 
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True
theme: readthedocs
theme_dir: 'custom_theme'
docs_dir: docs
site_dir: _site
copyright: <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />Content is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>. <br> Code is licensed under BSD 3-Clause.
